# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'mapbuilder/%Y_%m_%d_%h_%M_%s')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
