# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='title',
            new_name='name',
        ),
    ]
