# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapbuilder', '0003_auto_20180510_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='base_map_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'mapbuilder/%Y_%m_%d_%h_%M_%s/base/'),
        ),
    ]
