# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapbuilder', '0004_map_base_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='public',
            field=models.NullBooleanField(default=None),
        ),
    ]
