# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20170302_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='maxdate',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='mindate',
        ),
        migrations.RemoveField(
            model_name='lecturesegments',
            name='maxdate',
        ),
        migrations.RemoveField(
            model_name='lecturesegments',
            name='mindate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='autosubscribe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_signatures',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signature_html',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_zone',
        ),
    ]
