# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:21
from __future__ import unicode_literals

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('website', '0039_auto_20170415_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoonmodules',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lecturedocuments',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lecturesegments',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lectureslides',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='moduledocuments',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='tags',
        ),
        migrations.AddField(
            model_name='comingsoonmodules',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lecturedocuments',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lecturesegments',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lectureslides',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='moduledocuments',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='modules',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
