# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20170630_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledocuments',
            name='authors',
        ),
        migrations.AddField(
            model_name='comingsoonmodules',
            name='authors_m2m',
            field=models.ManyToManyField(to='website.profile'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='authors_m2m',
            field=models.ManyToManyField(to='website.profile'),
        ),
        migrations.AddField(
            model_name='modules',
            name='authors_m2m',
            field=models.ManyToManyField(to='website.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contributing',
            field=models.BooleanField(default=False),
        ),
    ]
