# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_profile_contributing'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'module_cover/%Y_%m_%d_%h_%M_%s'),
        ),
        migrations.AddField(
            model_name='modules',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
