# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_profile_contributing'),
    ]

    operations = [
        migrations.CreateModel(
            name='docType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lecturedocuments',
            name='doc_type',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_doc_type', to='website.docType'),
        ),
        migrations.AddField(
            model_name='moduledocuments',
            name='doc_type',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_doc_type', to='website.docType'),
        ),
    ]
