# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_comingsoonmodules_cover_image'),
        ('website', '0045_auto_20170804_1828'),
    ]

    operations = [
    ]
