# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('website', '0048_auto_20170822_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextHeavyPages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_heading', models.CharField(default=b'', max_length=255)),
                ('date', models.DateField(verbose_name=b'Updated On')),
                ('page_content', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('splash_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
