# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_textheavypages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textheavypages',
            name='page_heading',
        ),
    ]
