# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_remove_textheavypages_page_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='sidebarContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default=b'', max_length=255)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
        ),
    ]
